## Startup configuration for the {{ cookiecutter.package_name }} application in development mode
# on the host computer
version: '1.0'
main:
  host: 127.0.0.1
  port: 8080
  log_level: DEBUG
  enabled_developmen_mode: True
rest:
  version: {{cookiecutter.openapi_specs_version}}
  location: ${OSPARC_SIMCORE_REPO_ROOTDIR}/api/specs/{{cookiecutter.project_slug}}/{{cookiecutter.openapi_specs_version}}/openapi.yaml

## add here config sections for more service subsystems ...
